name: CI

on: [ push ]

env:
  RAILS_ENV: test
  RAILS_LOG_LEVEL: error

jobs:

  test:

    runs-on: ubuntu-latest

    needs: lint

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      -
        name: "Install Dependencies"
        run: bundle install --jobs 4 --retry 3
      -
        name: "Prepare Tests"
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:drop db:create db:schema:load
          bin/rails assets:precompile
      -
        name: "Test / Unit Tests (controllers, models, helpers, mailers, jobs, lib, requests)"
        run: bin/bundle exec rspec spec --exclude-pattern "spec/system/**/*_spec.rb"
      -
        name: "Test / System Tests"
        run: TEST_BROWSER=rack_test bin/bundle exec rspec spec/system

  lint:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
      -
        name: "Lint / rubocop"
        run: |
          gem install rubocop
          gem install rubocop-performance
          gem install rubocop-rake
          gem install rubocop-rspec
          gem install rubocop-rspec_rails
          gem install rubocop-rails
          gem install rubocop-capybara
          gem install rubocop-factory_bot
          rubocop --parallel
      -
        name: "Lint / erb_lint"
        run: bin/erb_lint --lint-all
      -
        name: "Security / brakeman"
        run: |
          gem install brakeman
          brakeman --exit-on-warn --no-progress --color --output /dev/stdout
      -
        name: "Security / bundle-audit"
        run: |
          gem install bundle-audit
          bundle-audit check --update -v
